# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iCheckIn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iCheckIn
  pod 'Firebase/Core'
   pod 'Firebase/AdMob'
   pod 'Firebase/Analytics'
   pod 'Firebase/AppIndexing'
   pod 'Firebase/Auth'
   pod 'Firebase/Crash'
   pod 'Firebase/Database'
   pod 'Firebase/DynamicLinks'
   pod 'Firebase/Invites'
   pod 'Firebase/Messaging'
   pod 'Firebase/RemoteConfig'
   pod 'Firebase/Storage'
   pod 'GoogleSignIn'

  target 'iCheckInTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iCheckInUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
